# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bylee/code/koi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bylee/code/koi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bylee/code/koi/CMakeFiles /Users/bylee/code/koi//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bylee/code/koi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_koi_queue

# Build rule for target.
test_koi_queue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_koi_queue
.PHONY : test_koi_queue

# fast build rule for target.
test_koi_queue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_koi_queue.dir/build.make CMakeFiles/test_koi_queue.dir/build
.PHONY : test_koi_queue/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named KoiCommonUtils

# Build rule for target.
KoiCommonUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KoiCommonUtils
.PHONY : KoiCommonUtils

# fast build rule for target.
KoiCommonUtils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KoiCommonUtils.dir/build.make CMakeFiles/KoiCommonUtils.dir/build
.PHONY : KoiCommonUtils/fast

#=============================================================================
# Target rules for targets named koi_bench

# Build rule for target.
koi_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 koi_bench
.PHONY : koi_bench

# fast build rule for target.
koi_bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/koi_bench.dir/build.make CMakeFiles/koi_bench.dir/build
.PHONY : koi_bench/fast

#=============================================================================
# Target rules for targets named boost_ipc

# Build rule for target.
boost_ipc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_ipc
.PHONY : boost_ipc

# fast build rule for target.
boost_ipc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_ipc.dir/build.make CMakeFiles/boost_ipc.dir/build
.PHONY : boost_ipc/fast

#=============================================================================
# Target rules for targets named BenchmarkUtils

# Build rule for target.
BenchmarkUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BenchmarkUtils
.PHONY : BenchmarkUtils

# fast build rule for target.
BenchmarkUtils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/build
.PHONY : BenchmarkUtils/fast

#=============================================================================
# Target rules for targets named ShmUtils

# Build rule for target.
ShmUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ShmUtils
.PHONY : ShmUtils

# fast build rule for target.
ShmUtils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShmUtils.dir/build.make CMakeFiles/ShmUtils.dir/build
.PHONY : ShmUtils/fast

#=============================================================================
# Target rules for targets named shm_client

# Build rule for target.
shm_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shm_client
.PHONY : shm_client

# fast build rule for target.
shm_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_client.dir/build.make CMakeFiles/shm_client.dir/build
.PHONY : shm_client/fast

#=============================================================================
# Target rules for targets named shm_server

# Build rule for target.
shm_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shm_server
.PHONY : shm_server

# fast build rule for target.
shm_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_server.dir/build.make CMakeFiles/shm_server.dir/build
.PHONY : shm_server/fast

#=============================================================================
# Target rules for targets named launcher

# Build rule for target.
launcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 launcher
.PHONY : launcher

# fast build rule for target.
launcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launcher.dir/build.make CMakeFiles/launcher.dir/build
.PHONY : launcher/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googlebenchmark-build/src/CMakeFiles/benchmark.dir/build.make _deps/googlebenchmark-build/src/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named benchmark_main

# Build rule for target.
benchmark_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_main
.PHONY : benchmark_main

# fast build rule for target.
benchmark_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googlebenchmark-build/src/CMakeFiles/benchmark_main.dir/build.make _deps/googlebenchmark-build/src/CMakeFiles/benchmark_main.dir/build
.PHONY : benchmark_main/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f _deps/spdlog-build/CMakeFiles/spdlog.dir/build.make _deps/spdlog-build/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named Boost_atomic

# Build rule for target.
Boost_atomic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_atomic
.PHONY : Boost_atomic

# fast build rule for target.
Boost_atomic/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_atomic.dir/build.make boost-cmake/CMakeFiles/Boost_atomic.dir/build
.PHONY : Boost_atomic/fast

#=============================================================================
# Target rules for targets named Boost_chrono

# Build rule for target.
Boost_chrono: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_chrono
.PHONY : Boost_chrono

# fast build rule for target.
Boost_chrono/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_chrono.dir/build.make boost-cmake/CMakeFiles/Boost_chrono.dir/build
.PHONY : Boost_chrono/fast

#=============================================================================
# Target rules for targets named Boost_container

# Build rule for target.
Boost_container: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_container
.PHONY : Boost_container

# fast build rule for target.
Boost_container/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_container.dir/build.make boost-cmake/CMakeFiles/Boost_container.dir/build
.PHONY : Boost_container/fast

#=============================================================================
# Target rules for targets named Boost_context

# Build rule for target.
Boost_context: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_context
.PHONY : Boost_context

# fast build rule for target.
Boost_context/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_context.dir/build.make boost-cmake/CMakeFiles/Boost_context.dir/build
.PHONY : Boost_context/fast

#=============================================================================
# Target rules for targets named Boost_coroutine

# Build rule for target.
Boost_coroutine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_coroutine
.PHONY : Boost_coroutine

# fast build rule for target.
Boost_coroutine/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_coroutine.dir/build.make boost-cmake/CMakeFiles/Boost_coroutine.dir/build
.PHONY : Boost_coroutine/fast

#=============================================================================
# Target rules for targets named Boost_date_time

# Build rule for target.
Boost_date_time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_date_time
.PHONY : Boost_date_time

# fast build rule for target.
Boost_date_time/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_date_time.dir/build.make boost-cmake/CMakeFiles/Boost_date_time.dir/build
.PHONY : Boost_date_time/fast

#=============================================================================
# Target rules for targets named Boost_exception

# Build rule for target.
Boost_exception: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_exception
.PHONY : Boost_exception

# fast build rule for target.
Boost_exception/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_exception.dir/build.make boost-cmake/CMakeFiles/Boost_exception.dir/build
.PHONY : Boost_exception/fast

#=============================================================================
# Target rules for targets named Boost_fiber

# Build rule for target.
Boost_fiber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_fiber
.PHONY : Boost_fiber

# fast build rule for target.
Boost_fiber/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_fiber.dir/build.make boost-cmake/CMakeFiles/Boost_fiber.dir/build
.PHONY : Boost_fiber/fast

#=============================================================================
# Target rules for targets named Boost_filesystem

# Build rule for target.
Boost_filesystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_filesystem
.PHONY : Boost_filesystem

# fast build rule for target.
Boost_filesystem/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_filesystem.dir/build.make boost-cmake/CMakeFiles/Boost_filesystem.dir/build
.PHONY : Boost_filesystem/fast

#=============================================================================
# Target rules for targets named Boost_iostreams

# Build rule for target.
Boost_iostreams: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_iostreams
.PHONY : Boost_iostreams

# fast build rule for target.
Boost_iostreams/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_iostreams.dir/build.make boost-cmake/CMakeFiles/Boost_iostreams.dir/build
.PHONY : Boost_iostreams/fast

#=============================================================================
# Target rules for targets named Boost_log

# Build rule for target.
Boost_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_log
.PHONY : Boost_log

# fast build rule for target.
Boost_log/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_log.dir/build.make boost-cmake/CMakeFiles/Boost_log.dir/build
.PHONY : Boost_log/fast

#=============================================================================
# Target rules for targets named Boost_log_setup

# Build rule for target.
Boost_log_setup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_log_setup
.PHONY : Boost_log_setup

# fast build rule for target.
Boost_log_setup/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_log_setup.dir/build.make boost-cmake/CMakeFiles/Boost_log_setup.dir/build
.PHONY : Boost_log_setup/fast

#=============================================================================
# Target rules for targets named Boost_math

# Build rule for target.
Boost_math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_math
.PHONY : Boost_math

# fast build rule for target.
Boost_math/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_math.dir/build.make boost-cmake/CMakeFiles/Boost_math.dir/build
.PHONY : Boost_math/fast

#=============================================================================
# Target rules for targets named Boost_program_options

# Build rule for target.
Boost_program_options: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_program_options
.PHONY : Boost_program_options

# fast build rule for target.
Boost_program_options/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_program_options.dir/build.make boost-cmake/CMakeFiles/Boost_program_options.dir/build
.PHONY : Boost_program_options/fast

#=============================================================================
# Target rules for targets named Boost_random

# Build rule for target.
Boost_random: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_random
.PHONY : Boost_random

# fast build rule for target.
Boost_random/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_random.dir/build.make boost-cmake/CMakeFiles/Boost_random.dir/build
.PHONY : Boost_random/fast

#=============================================================================
# Target rules for targets named Boost_serialization

# Build rule for target.
Boost_serialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_serialization
.PHONY : Boost_serialization

# fast build rule for target.
Boost_serialization/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_serialization.dir/build.make boost-cmake/CMakeFiles/Boost_serialization.dir/build
.PHONY : Boost_serialization/fast

#=============================================================================
# Target rules for targets named Boost_system

# Build rule for target.
Boost_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_system
.PHONY : Boost_system

# fast build rule for target.
Boost_system/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_system.dir/build.make boost-cmake/CMakeFiles/Boost_system.dir/build
.PHONY : Boost_system/fast

#=============================================================================
# Target rules for targets named Boost_unit_test_framework

# Build rule for target.
Boost_unit_test_framework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_unit_test_framework
.PHONY : Boost_unit_test_framework

# fast build rule for target.
Boost_unit_test_framework/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_unit_test_framework.dir/build.make boost-cmake/CMakeFiles/Boost_unit_test_framework.dir/build
.PHONY : Boost_unit_test_framework/fast

#=============================================================================
# Target rules for targets named Boost_thread

# Build rule for target.
Boost_thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_thread
.PHONY : Boost_thread

# fast build rule for target.
Boost_thread/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_thread.dir/build.make boost-cmake/CMakeFiles/Boost_thread.dir/build
.PHONY : Boost_thread/fast

#=============================================================================
# Target rules for targets named Boost_timer

# Build rule for target.
Boost_timer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_timer
.PHONY : Boost_timer

# fast build rule for target.
Boost_timer/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_timer.dir/build.make boost-cmake/CMakeFiles/Boost_timer.dir/build
.PHONY : Boost_timer/fast

#=============================================================================
# Target rules for targets named Boost_type_erasure

# Build rule for target.
Boost_type_erasure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_type_erasure
.PHONY : Boost_type_erasure

# fast build rule for target.
Boost_type_erasure/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_type_erasure.dir/build.make boost-cmake/CMakeFiles/Boost_type_erasure.dir/build
.PHONY : Boost_type_erasure/fast

#=============================================================================
# Target rules for targets named Boost_wave

# Build rule for target.
Boost_wave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Boost_wave
.PHONY : Boost_wave

# fast build rule for target.
Boost_wave/fast:
	$(MAKE) $(MAKESILENT) -f boost-cmake/CMakeFiles/Boost_wave.dir/build.make boost-cmake/CMakeFiles/Boost_wave.dir/build
.PHONY : Boost_wave/fast

benchmarks/boost/boost_benchmarks.o: benchmarks/boost/boost_benchmarks.cc.o
.PHONY : benchmarks/boost/boost_benchmarks.o

# target to build an object file
benchmarks/boost/boost_benchmarks.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_ipc.dir/build.make CMakeFiles/boost_ipc.dir/benchmarks/boost/boost_benchmarks.cc.o
.PHONY : benchmarks/boost/boost_benchmarks.cc.o

benchmarks/boost/boost_benchmarks.i: benchmarks/boost/boost_benchmarks.cc.i
.PHONY : benchmarks/boost/boost_benchmarks.i

# target to preprocess a source file
benchmarks/boost/boost_benchmarks.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_ipc.dir/build.make CMakeFiles/boost_ipc.dir/benchmarks/boost/boost_benchmarks.cc.i
.PHONY : benchmarks/boost/boost_benchmarks.cc.i

benchmarks/boost/boost_benchmarks.s: benchmarks/boost/boost_benchmarks.cc.s
.PHONY : benchmarks/boost/boost_benchmarks.s

# target to generate assembly for a file
benchmarks/boost/boost_benchmarks.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/boost_ipc.dir/build.make CMakeFiles/boost_ipc.dir/benchmarks/boost/boost_benchmarks.cc.s
.PHONY : benchmarks/boost/boost_benchmarks.cc.s

benchmarks/common/args.o: benchmarks/common/args.cc.o
.PHONY : benchmarks/common/args.o

# target to build an object file
benchmarks/common/args.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/args.cc.o
.PHONY : benchmarks/common/args.cc.o

benchmarks/common/args.i: benchmarks/common/args.cc.i
.PHONY : benchmarks/common/args.i

# target to preprocess a source file
benchmarks/common/args.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/args.cc.i
.PHONY : benchmarks/common/args.cc.i

benchmarks/common/args.s: benchmarks/common/args.cc.s
.PHONY : benchmarks/common/args.s

# target to generate assembly for a file
benchmarks/common/args.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/args.cc.s
.PHONY : benchmarks/common/args.cc.s

benchmarks/common/bench.o: benchmarks/common/bench.cc.o
.PHONY : benchmarks/common/bench.o

# target to build an object file
benchmarks/common/bench.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/bench.cc.o
.PHONY : benchmarks/common/bench.cc.o

benchmarks/common/bench.i: benchmarks/common/bench.cc.i
.PHONY : benchmarks/common/bench.i

# target to preprocess a source file
benchmarks/common/bench.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/bench.cc.i
.PHONY : benchmarks/common/bench.cc.i

benchmarks/common/bench.s: benchmarks/common/bench.cc.s
.PHONY : benchmarks/common/bench.s

# target to generate assembly for a file
benchmarks/common/bench.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/bench.cc.s
.PHONY : benchmarks/common/bench.cc.s

benchmarks/common/launcher.o: benchmarks/common/launcher.cc.o
.PHONY : benchmarks/common/launcher.o

# target to build an object file
benchmarks/common/launcher.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launcher.dir/build.make CMakeFiles/launcher.dir/benchmarks/common/launcher.cc.o
.PHONY : benchmarks/common/launcher.cc.o

benchmarks/common/launcher.i: benchmarks/common/launcher.cc.i
.PHONY : benchmarks/common/launcher.i

# target to preprocess a source file
benchmarks/common/launcher.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launcher.dir/build.make CMakeFiles/launcher.dir/benchmarks/common/launcher.cc.i
.PHONY : benchmarks/common/launcher.cc.i

benchmarks/common/launcher.s: benchmarks/common/launcher.cc.s
.PHONY : benchmarks/common/launcher.s

# target to generate assembly for a file
benchmarks/common/launcher.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launcher.dir/build.make CMakeFiles/launcher.dir/benchmarks/common/launcher.cc.s
.PHONY : benchmarks/common/launcher.cc.s

benchmarks/common/signals.o: benchmarks/common/signals.cc.o
.PHONY : benchmarks/common/signals.o

# target to build an object file
benchmarks/common/signals.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KoiCommonUtils.dir/build.make CMakeFiles/KoiCommonUtils.dir/benchmarks/common/signals.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/signals.cc.o
.PHONY : benchmarks/common/signals.cc.o

benchmarks/common/signals.i: benchmarks/common/signals.cc.i
.PHONY : benchmarks/common/signals.i

# target to preprocess a source file
benchmarks/common/signals.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KoiCommonUtils.dir/build.make CMakeFiles/KoiCommonUtils.dir/benchmarks/common/signals.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/signals.cc.i
.PHONY : benchmarks/common/signals.cc.i

benchmarks/common/signals.s: benchmarks/common/signals.cc.s
.PHONY : benchmarks/common/signals.s

# target to generate assembly for a file
benchmarks/common/signals.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KoiCommonUtils.dir/build.make CMakeFiles/KoiCommonUtils.dir/benchmarks/common/signals.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/signals.cc.s
.PHONY : benchmarks/common/signals.cc.s

benchmarks/common/utils.o: benchmarks/common/utils.cc.o
.PHONY : benchmarks/common/utils.o

# target to build an object file
benchmarks/common/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/utils.cc.o
.PHONY : benchmarks/common/utils.cc.o

benchmarks/common/utils.i: benchmarks/common/utils.cc.i
.PHONY : benchmarks/common/utils.i

# target to preprocess a source file
benchmarks/common/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/utils.cc.i
.PHONY : benchmarks/common/utils.cc.i

benchmarks/common/utils.s: benchmarks/common/utils.cc.s
.PHONY : benchmarks/common/utils.s

# target to generate assembly for a file
benchmarks/common/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BenchmarkUtils.dir/build.make CMakeFiles/BenchmarkUtils.dir/benchmarks/common/utils.cc.s
.PHONY : benchmarks/common/utils.cc.s

benchmarks/koi_queue/koi_benchmarks.o: benchmarks/koi_queue/koi_benchmarks.cc.o
.PHONY : benchmarks/koi_queue/koi_benchmarks.o

# target to build an object file
benchmarks/koi_queue/koi_benchmarks.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/koi_bench.dir/build.make CMakeFiles/koi_bench.dir/benchmarks/koi_queue/koi_benchmarks.cc.o
.PHONY : benchmarks/koi_queue/koi_benchmarks.cc.o

benchmarks/koi_queue/koi_benchmarks.i: benchmarks/koi_queue/koi_benchmarks.cc.i
.PHONY : benchmarks/koi_queue/koi_benchmarks.i

# target to preprocess a source file
benchmarks/koi_queue/koi_benchmarks.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/koi_bench.dir/build.make CMakeFiles/koi_bench.dir/benchmarks/koi_queue/koi_benchmarks.cc.i
.PHONY : benchmarks/koi_queue/koi_benchmarks.cc.i

benchmarks/koi_queue/koi_benchmarks.s: benchmarks/koi_queue/koi_benchmarks.cc.s
.PHONY : benchmarks/koi_queue/koi_benchmarks.s

# target to generate assembly for a file
benchmarks/koi_queue/koi_benchmarks.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/koi_bench.dir/build.make CMakeFiles/koi_bench.dir/benchmarks/koi_queue/koi_benchmarks.cc.s
.PHONY : benchmarks/koi_queue/koi_benchmarks.cc.s

benchmarks/shm/client.o: benchmarks/shm/client.cc.o
.PHONY : benchmarks/shm/client.o

# target to build an object file
benchmarks/shm/client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_client.dir/build.make CMakeFiles/shm_client.dir/benchmarks/shm/client.cc.o
.PHONY : benchmarks/shm/client.cc.o

benchmarks/shm/client.i: benchmarks/shm/client.cc.i
.PHONY : benchmarks/shm/client.i

# target to preprocess a source file
benchmarks/shm/client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_client.dir/build.make CMakeFiles/shm_client.dir/benchmarks/shm/client.cc.i
.PHONY : benchmarks/shm/client.cc.i

benchmarks/shm/client.s: benchmarks/shm/client.cc.s
.PHONY : benchmarks/shm/client.s

# target to generate assembly for a file
benchmarks/shm/client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_client.dir/build.make CMakeFiles/shm_client.dir/benchmarks/shm/client.cc.s
.PHONY : benchmarks/shm/client.cc.s

benchmarks/shm/server.o: benchmarks/shm/server.cc.o
.PHONY : benchmarks/shm/server.o

# target to build an object file
benchmarks/shm/server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_server.dir/build.make CMakeFiles/shm_server.dir/benchmarks/shm/server.cc.o
.PHONY : benchmarks/shm/server.cc.o

benchmarks/shm/server.i: benchmarks/shm/server.cc.i
.PHONY : benchmarks/shm/server.i

# target to preprocess a source file
benchmarks/shm/server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_server.dir/build.make CMakeFiles/shm_server.dir/benchmarks/shm/server.cc.i
.PHONY : benchmarks/shm/server.cc.i

benchmarks/shm/server.s: benchmarks/shm/server.cc.s
.PHONY : benchmarks/shm/server.s

# target to generate assembly for a file
benchmarks/shm/server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shm_server.dir/build.make CMakeFiles/shm_server.dir/benchmarks/shm/server.cc.s
.PHONY : benchmarks/shm/server.cc.s

benchmarks/shm/shm.o: benchmarks/shm/shm.cc.o
.PHONY : benchmarks/shm/shm.o

# target to build an object file
benchmarks/shm/shm.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShmUtils.dir/build.make CMakeFiles/ShmUtils.dir/benchmarks/shm/shm.cc.o
.PHONY : benchmarks/shm/shm.cc.o

benchmarks/shm/shm.i: benchmarks/shm/shm.cc.i
.PHONY : benchmarks/shm/shm.i

# target to preprocess a source file
benchmarks/shm/shm.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShmUtils.dir/build.make CMakeFiles/ShmUtils.dir/benchmarks/shm/shm.cc.i
.PHONY : benchmarks/shm/shm.cc.i

benchmarks/shm/shm.s: benchmarks/shm/shm.cc.s
.PHONY : benchmarks/shm/shm.s

# target to generate assembly for a file
benchmarks/shm/shm.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShmUtils.dir/build.make CMakeFiles/ShmUtils.dir/benchmarks/shm/shm.cc.s
.PHONY : benchmarks/shm/shm.cc.s

cpp/common/logger.o: cpp/common/logger.cc.o
.PHONY : cpp/common/logger.o

# target to build an object file
cpp/common/logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KoiCommonUtils.dir/build.make CMakeFiles/KoiCommonUtils.dir/cpp/common/logger.cc.o
.PHONY : cpp/common/logger.cc.o

cpp/common/logger.i: cpp/common/logger.cc.i
.PHONY : cpp/common/logger.i

# target to preprocess a source file
cpp/common/logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KoiCommonUtils.dir/build.make CMakeFiles/KoiCommonUtils.dir/cpp/common/logger.cc.i
.PHONY : cpp/common/logger.cc.i

cpp/common/logger.s: cpp/common/logger.cc.s
.PHONY : cpp/common/logger.s

# target to generate assembly for a file
cpp/common/logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KoiCommonUtils.dir/build.make CMakeFiles/KoiCommonUtils.dir/cpp/common/logger.cc.s
.PHONY : cpp/common/logger.cc.s

tests/fixed_size/koi_queue/test_multiprocess.o: tests/fixed_size/koi_queue/test_multiprocess.cpp.o
.PHONY : tests/fixed_size/koi_queue/test_multiprocess.o

# target to build an object file
tests/fixed_size/koi_queue/test_multiprocess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_koi_queue.dir/build.make CMakeFiles/test_koi_queue.dir/tests/fixed_size/koi_queue/test_multiprocess.cpp.o
.PHONY : tests/fixed_size/koi_queue/test_multiprocess.cpp.o

tests/fixed_size/koi_queue/test_multiprocess.i: tests/fixed_size/koi_queue/test_multiprocess.cpp.i
.PHONY : tests/fixed_size/koi_queue/test_multiprocess.i

# target to preprocess a source file
tests/fixed_size/koi_queue/test_multiprocess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_koi_queue.dir/build.make CMakeFiles/test_koi_queue.dir/tests/fixed_size/koi_queue/test_multiprocess.cpp.i
.PHONY : tests/fixed_size/koi_queue/test_multiprocess.cpp.i

tests/fixed_size/koi_queue/test_multiprocess.s: tests/fixed_size/koi_queue/test_multiprocess.cpp.s
.PHONY : tests/fixed_size/koi_queue/test_multiprocess.s

# target to generate assembly for a file
tests/fixed_size/koi_queue/test_multiprocess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_koi_queue.dir/build.make CMakeFiles/test_koi_queue.dir/tests/fixed_size/koi_queue/test_multiprocess.cpp.s
.PHONY : tests/fixed_size/koi_queue/test_multiprocess.cpp.s

tests/fixed_size/koi_queue/test_single_thread.o: tests/fixed_size/koi_queue/test_single_thread.cpp.o
.PHONY : tests/fixed_size/koi_queue/test_single_thread.o

# target to build an object file
tests/fixed_size/koi_queue/test_single_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_koi_queue.dir/build.make CMakeFiles/test_koi_queue.dir/tests/fixed_size/koi_queue/test_single_thread.cpp.o
.PHONY : tests/fixed_size/koi_queue/test_single_thread.cpp.o

tests/fixed_size/koi_queue/test_single_thread.i: tests/fixed_size/koi_queue/test_single_thread.cpp.i
.PHONY : tests/fixed_size/koi_queue/test_single_thread.i

# target to preprocess a source file
tests/fixed_size/koi_queue/test_single_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_koi_queue.dir/build.make CMakeFiles/test_koi_queue.dir/tests/fixed_size/koi_queue/test_single_thread.cpp.i
.PHONY : tests/fixed_size/koi_queue/test_single_thread.cpp.i

tests/fixed_size/koi_queue/test_single_thread.s: tests/fixed_size/koi_queue/test_single_thread.cpp.s
.PHONY : tests/fixed_size/koi_queue/test_single_thread.s

# target to generate assembly for a file
tests/fixed_size/koi_queue/test_single_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_koi_queue.dir/build.make CMakeFiles/test_koi_queue.dir/tests/fixed_size/koi_queue/test_single_thread.cpp.s
.PHONY : tests/fixed_size/koi_queue/test_single_thread.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... BenchmarkUtils"
	@echo "... Boost_atomic"
	@echo "... Boost_chrono"
	@echo "... Boost_container"
	@echo "... Boost_context"
	@echo "... Boost_coroutine"
	@echo "... Boost_date_time"
	@echo "... Boost_exception"
	@echo "... Boost_fiber"
	@echo "... Boost_filesystem"
	@echo "... Boost_iostreams"
	@echo "... Boost_log"
	@echo "... Boost_log_setup"
	@echo "... Boost_math"
	@echo "... Boost_program_options"
	@echo "... Boost_random"
	@echo "... Boost_serialization"
	@echo "... Boost_system"
	@echo "... Boost_thread"
	@echo "... Boost_timer"
	@echo "... Boost_type_erasure"
	@echo "... Boost_unit_test_framework"
	@echo "... Boost_wave"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... KoiCommonUtils"
	@echo "... ShmUtils"
	@echo "... benchmark"
	@echo "... benchmark_main"
	@echo "... boost_ipc"
	@echo "... koi_bench"
	@echo "... launcher"
	@echo "... shm_client"
	@echo "... shm_server"
	@echo "... spdlog"
	@echo "... test_koi_queue"
	@echo "... benchmarks/boost/boost_benchmarks.o"
	@echo "... benchmarks/boost/boost_benchmarks.i"
	@echo "... benchmarks/boost/boost_benchmarks.s"
	@echo "... benchmarks/common/args.o"
	@echo "... benchmarks/common/args.i"
	@echo "... benchmarks/common/args.s"
	@echo "... benchmarks/common/bench.o"
	@echo "... benchmarks/common/bench.i"
	@echo "... benchmarks/common/bench.s"
	@echo "... benchmarks/common/launcher.o"
	@echo "... benchmarks/common/launcher.i"
	@echo "... benchmarks/common/launcher.s"
	@echo "... benchmarks/common/signals.o"
	@echo "... benchmarks/common/signals.i"
	@echo "... benchmarks/common/signals.s"
	@echo "... benchmarks/common/utils.o"
	@echo "... benchmarks/common/utils.i"
	@echo "... benchmarks/common/utils.s"
	@echo "... benchmarks/koi_queue/koi_benchmarks.o"
	@echo "... benchmarks/koi_queue/koi_benchmarks.i"
	@echo "... benchmarks/koi_queue/koi_benchmarks.s"
	@echo "... benchmarks/shm/client.o"
	@echo "... benchmarks/shm/client.i"
	@echo "... benchmarks/shm/client.s"
	@echo "... benchmarks/shm/server.o"
	@echo "... benchmarks/shm/server.i"
	@echo "... benchmarks/shm/server.s"
	@echo "... benchmarks/shm/shm.o"
	@echo "... benchmarks/shm/shm.i"
	@echo "... benchmarks/shm/shm.s"
	@echo "... cpp/common/logger.o"
	@echo "... cpp/common/logger.i"
	@echo "... cpp/common/logger.s"
	@echo "... tests/fixed_size/koi_queue/test_multiprocess.o"
	@echo "... tests/fixed_size/koi_queue/test_multiprocess.i"
	@echo "... tests/fixed_size/koi_queue/test_multiprocess.s"
	@echo "... tests/fixed_size/koi_queue/test_single_thread.o"
	@echo "... tests/fixed_size/koi_queue/test_single_thread.i"
	@echo "... tests/fixed_size/koi_queue/test_single_thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

